.PHONY: help
help:
	@echo "  make install              # runs bin/install.sh (override with INSTALL_ARGS=\"...\")"
	@echo "  make clean                # runs bin/clean.sh"
	@echo "  make clean-full           # runs bin/clean.sh --full"
	@echo "  make runtime              # builds the native runtime library"
	@echo "  make runtime-android      # builds the Android runtime variant"
	@echo "  make compile-flags        # regenerates compile_flags.txt"
	@echo "  make gen                  # regenerates docs and typings"
	@echo "  make gen-docs             # regenerates docs only"
	@echo "  make gen-types            # regenerates TypeScript declarations"
	@echo "  make docs-diagrams        # renders Mermaid diagrams to SVG"
	@echo "  make docs-diagrams-png    # renders Mermaid diagrams to PNG"
	@echo "  make test                 # runs desktop tests"
	@echo "  make test-runtime-core    # runs runtime-core tests"
	@echo "  make test-lint            # runs StandardJS lint"
	@echo "  make test-ios-simulator   # runs iOS simulator tests"
	@echo "  make test-android         # runs Android tests"
	@echo "  make test-android-emulator# runs Android emulator tests"
	@echo "  make relink               # runs npm relink helper"
	@echo "  make publish              # runs bin/publish-npm-modules.sh"
	@echo "  make update-protocol      # updates the network protocol bundle"
