#ifndef ORO_RUNTIME_PLATFORM_H
#define ORO_RUNTIME_PLATFORM_H

#ifndef ORO_RUNTIME_PLATFORM
#define ORO_RUNTIME_PLATFORM 1

// when this header is included, this is always `0`
#define ORO_RUNTIME_PLATFORM_WASM 0

#if defined(__x86_64__) || defined(_M_X64)
#  define ORO_RUNTIME_PLATFORM_ARCH_x64 1
#  define ORO_RUNTIME_PLATFORM_ARCH_ARM64 0
#  define ORO_RUNTIME_PLATFORM_ARCH_UNKNOWN 0
#elif defined(__aarch64__) || defined(_M_ARM64)
#  define ORO_RUNTIME_PLATFORM_ARCH_x64 0
#  define ORO_RUNTIME_PLATFORM_ARCH_ARM64 1
#  define ORO_RUNTIME_PLATFORM_ARCH_UNKNOWN 0
#elif defined(__i386__) && !defined(__ANDROID__)
#error Socket is not supported on i386.
#else
#  define ORO_RUNTIME_PLATFORM_ARCH_x64 0
#  define ORO_RUNTIME_PLATFORM_ARCH_ARM64 0
#  define ORO_RUNTIME_PLATFORM_ARCH_UNKNOWN 1
#endif

#if defined(_WIN32)
# define ORO_RUNTIME_PLATFORM_NAME "win32"
# define ORO_RUNTIME_PLATFORM_OS "win32"
# define ORO_RUNTIME_PLATFORM_ANDROID 0
# define ORO_RUNTIME_PLATFORM_APPLE 0
# define ORO_RUNTIME_PLATFORM_IOS 0
# define ORO_RUNTIME_PLATFORM_IOS_SIMULATOR 0
# define ORO_RUNTIME_PLATFORM_LINUX 0
# define ORO_RUNTIME_PLATFORM_MACOS 0
# define ORO_RUNTIME_PLATFORM_UNIX 0
# define ORO_RUNTIME_PLATFORM_WINDOWS 1
# define ORO_RUNTIME_PLATFORM_BSD 0
# define ORO_RUNTIME_PLATFORM_FREEBSD 0
# define ORO_RUNTIME_PLATFORM_OPENBSD 0
#elif defined(__APPLE__)
# include <TargetConditionals.h>
# define ORO_RUNTIME_PLATFORM_APPLE 1
# define ORO_RUNTIME_PLATFORM_NAME "darwin"
# define ORO_RUNTIME_PLATFORM_ANDROID 0
# define ORO_RUNTIME_PLATFORM_IOS_SIMULATOR 0
# define ORO_RUNTIME_PLATFORM_LINUX 0
# define ORO_RUNTIME_PLATFORM_WINDOWS 0
# define ORO_RUNTIME_PLATFORM_BSD 0
# define ORO_RUNTIME_PLATFORM_FREEBSD 0
# define ORO_RUNTIME_PLATFORM_OPENBSD 0

#if TARGET_OS_IPHONE
# define ORO_RUNTIME_PLATFORM_MACOS 0
# define ORO_RUNTIME_PLATFORM_IOS 1
# define ORO_RUNTIME_PLATFORM_IOS_SIMULATOR 0
# define ORO_RUNTIME_PLATFORM_OS "ios"
#elif TARGET_IPHONE_SIMULATOR
# define ORO_RUNTIME_PLATFORM_MACOS 0
# define ORO_RUNTIME_PLATFORM_IOS 1
# define ORO_RUNTIME_PLATFORM_IOS_SIMULATOR 1
# define ORO_RUNTIME_PLATFORM_OS "ios"
#else
# define ORO_RUNTIME_PLATFORM_MACOS 1
# define ORO_RUNTIME_PLATFORM_IOS 0
# define ORO_RUNTIME_PLATFORM_IOS_SIMULATOR 0
# define ORO_RUNTIME_PLATFORM_OS "mac"
#endif

#if defined(__unix__) || defined(unix) || defined(__unix)
# define ORO_RUNTIME_PLATFORM_UNIX 1
#else
# define ORO_RUNTIME_PLATFORM_UNIX 0
#endif

#elif defined(__linux__)
# undef linux
# define ORO_RUNTIME_PLATFORM_NAME "linux"
# define ORO_RUNTIME_PLATFORM_APPLE 0
# define ORO_RUNTIME_PLATFORM_IOS 0
# define ORO_RUNTIME_PLATFORM_IOS_SIMULATOR 0
# define ORO_RUNTIME_PLATFORM_MACOS 0
# define ORO_RUNTIME_PLATFORM_WINDOWS 0
# define ORO_RUNTIME_PLATFORM_BSD 0
# define ORO_RUNTIME_PLATFORM_FREEBSD 0
# define ORO_RUNTIME_PLATFORM_OPENBSD 0

#ifdef __ANDROID__
# define ORO_RUNTIME_PLATFORM_OS "android"
# define ORO_RUNTIME_PLATFORM_ANDROID 1
# define ORO_RUNTIME_PLATFORM_LINUX 0
#else
# define ORO_RUNTIME_PLATFORM_OS "linux"
# define ORO_RUNTIME_PLATFORM_ANDROID 0
# define ORO_RUNTIME_PLATFORM_LINUX 1
#endif

#if defined(__unix__) || defined(unix) || defined(__unix)
# define ORO_RUNTIME_PLATFORM_UNIX 1
#else
# define ORO_RUNTIME_PLATFORM_UNIX 0
#endif

#elif defined(__FreeBSD__)
# define ORO_RUNTIME_PLATFORM_NAME "freebsd"
# define ORO_RUNTIME_PLATFORM_OS "freebsd"
# define ORO_RUNTIME_PLATFORM_ANDROID 0
# define ORO_RUNTIME_PLATFORM_IOS 0
# define ORO_RUNTIME_PLATFORM_IOS_SIMULATOR 0
# define ORO_RUNTIME_PLATFORM_LINUX 0
# define ORO_RUNTIME_PLATFORM_MACOS 0
# define ORO_RUNTIME_PLATFORM_WINDOWS 0
# define ORO_RUNTIME_PLATFORM_BSD 1
# define ORO_RUNTIME_PLATFORM_FREEBSD 1
# define ORO_RUNTIME_PLATFORM_OPENBSD 0

# define ORO_RUNTIME_PLATFORM_UNIX 1

#elif defined(BSD)
# define ORO_RUNTIME_PLATFORM_NAME "openbsd"
# define ORO_RUNTIME_PLATFORM_OS "openbsd"
# define ORO_RUNTIME_PLATFORM_ANDROID 0
# define ORO_RUNTIME_PLATFORM_APPLE 0
# define ORO_RUNTIME_PLATFORM_IOS 0
# define ORO_RUNTIME_PLATFORM_IOS_SIMULATOR 0
# define ORO_RUNTIME_PLATFORM_LINUX 0
# define ORO_RUNTIME_PLATFORM_MACOS 0
# define ORO_RUNTIME_PLATFORM_WINDOWS 0

# define ORO_RUNTIME_PLATFORM_BSD 1
# define ORO_RUNTIME_PLATFORM_FREEBSD 0
# define ORO_RUNTIME_PLATFORM_OPENBSD 1
# define ORO_RUNTIME_PLATFORM_UNIX 1
#else
# define ORO_RUNTIME_PLATFORM_NAME "unknown"
# define ORO_RUNTIME_PLATFORM_OS "unknown"
# define ORO_RUNTIME_PLATFORM_ANDROID 0
# define ORO_RUNTIME_PLATFORM_APPLE 0
# define ORO_RUNTIME_PLATFORM_BSD 0
# define ORO_RUNTIME_PLATFORM_FREEBSD 0
# define ORO_RUNTIME_PLATFORM_OPENBSD 0
# define ORO_RUNTIME_PLATFORM_IOS 0
# define ORO_RUNTIME_PLATFORM_IOS_SIMULATOR 0
# define ORO_RUNTIME_PLATFORM_LINUX 0
# define ORO_RUNTIME_PLATFORM_MACOS 0
# define ORO_RUNTIME_PLATFORM_WINDOWS 0
# define ORO_RUNTIME_PLATFORM_UNIX 0
#endif

#if ORO_RUNTIME_PLATFORM_ANDROID || ORO_RUNTIME_PLATFORM_IOS
#define ORO_RUNTIME_PLATFORM_MOBILE 1
#define ORO_RUNTIME_PLATFORM_DESKTOP 0
#else
#define ORO_RUNTIME_PLATFORM_MOBILE 0
#define ORO_RUNTIME_PLATFORM_DESKTOP 1
#endif

#if !defined(ORO_RUNTIME_PLATFORM_SANDBOXED)
#define ORO_RUNTIME_PLATFORM_SANDBOXED 0
#endif
#if !defined(ORO_RUNTIME_PLATFORM_ANDROID)
#define ORO_RUNTIME_PLATFORM_ANDROID 0
#endif
#if !defined(ORO_RUNTIME_PLATFORM_APPLE)
#define ORO_RUNTIME_PLATFORM_APPLE 0
#endif
#if !defined(ORO_RUNTIME_PLATFORM_BSD)
#define ORO_RUNTIME_PLATFORM_BSD 0
#endif
#if !defined(ORO_RUNTIME_PLATFORM_FREEBSD)
#define ORO_RUNTIME_PLATFORM_FREEBSD 0
#endif
#if !defined(ORO_RUNTIME_PLATFORM_OPENBSD)
#define ORO_RUNTIME_PLATFORM_OPENBSD 0
#endif
#if !defined(ORO_RUNTIME_PLATFORM_IOS)
#define ORO_RUNTIME_PLATFORM_IOS 0
#endif
#if !defined(ORO_RUNTIME_PLATFORM_IOS_SIMULATOR)
#define ORO_RUNTIME_PLATFORM_IOS_SIMULATOR 0
#endif
#if !defined(ORO_RUNTIME_PLATFORM_LINUX)
#define ORO_RUNTIME_PLATFORM_LINUX 0
#endif
#if !defined(ORO_RUNTIME_PLATFORM_MACOS)
#define ORO_RUNTIME_PLATFORM_MACOS 0
#endif
#if !defined(ORO_RUNTIME_PLATFORM_WINDOWS)
#define ORO_RUNTIME_PLATFORM_WINDOWS 0
#endif
#if !defined(ORO_RUNTIME_PLATFORM_UNIX)
#define ORO_RUNTIME_PLATFORM_UNIX 0
#endif
#if !defined(ORO_RUNTIME_PLATFORM_NAME)
#define ORO_RUNTIME_PLATFORM_NAME "unknown"
#endif
#if !defined(ORO_RUNTIME_PLATFORM_OS)
#define ORO_RUNTIME_PLATFORM_OS "unknown"
#endif

#define ORO_RUNTIME_PLATFORM_POSIX ORO_RUNTIME_PLATFORM_UNIX
#define ORO_RUNTIME_PLATFORM_DARWIN ORO_RUNTIME_PLATFORM_APPLE
#define ORO_RUNTIME_PLATFORM_IS(name) (ORO_RUNTIME_PLATFORM_##name)

#if !defined(ORO_RUNTIME_PLATFORM_WANTS_MINGW)
#define ORO_RUNTIME_PLATFORM_WANTS_MINGW 0
#endif

#if !defined(ORO_RUNTIME_CROSS_COMPILED_HOST)
#define ORO_RUNTIME_CROSS_COMPILED_HOST 0
#endif

#endif

#endif
