export default exports;
import * as mounts from './mounts.js';
import * as posix from './posix.js';
import * as win32 from './win32.js';
import { Path } from './path.js';
import { DOWNLOADS } from './well-known.js';
import { DOCUMENTS } from './well-known.js';
import { RESOURCES } from './well-known.js';
import { PICTURES } from './well-known.js';
import { DESKTOP } from './well-known.js';
import { VIDEOS } from './well-known.js';
import { CONFIG } from './well-known.js';
import { MEDIA } from './well-known.js';
import { MUSIC } from './well-known.js';
import { HOME } from './well-known.js';
import { DATA } from './well-known.js';
import { LOG } from './well-known.js';
import { TMP } from './well-known.js';
import * as exports from './index.js';
export { mounts, posix, win32, Path, DOWNLOADS, DOCUMENTS, RESOURCES, PICTURES, DESKTOP, VIDEOS, CONFIG, MEDIA, MUSIC, HOME, DATA, LOG, TMP };
