.TH ORO-SERVICE-WORKER-GLOBAL 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:service\-worker/global \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:service\-worker/global'
.fi
.SH DESCRIPTION
.PP
oro:service\-worker/global is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBServiceWorkerGlobalScope\fR
This is an exported `ClassDeclaration` named `ServiceWorkerGlobalScope`, but it does not yet have a dedicated description in the generated reference.
