.TH ORO-PROTOCOL-HANDLERS 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:protocol\-handlers \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:protocol\-handlers'
.fi
.SH DESCRIPTION
.PP
oro:protocol\-handlers is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBgetServiceWorker(options)\fR
/**
\fBParameters:\fR
.br
\fIoptions\fR (GetServiceWorkerOptions; required)
