.TH ORO-DIAGNOSTICS 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:diagnostics \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:diagnostics'
.fi
.SH DESCRIPTION
.PP
oro:diagnostics is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBchannel(name)\fR
Documented function exposed by this module.
\fBParameters:\fR
.br
\fIname\fR (string; required)
\fBReturns:\fR
.br
\fIimport('./channels.js').Channel\fR
