.TH ORO-MIME-PARAMS 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:mime/params \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:mime/params'
.fi
.SH DESCRIPTION
.PP
oro:mime/params is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBMIMEParams (extends Map)\fR
This is an exported `ClassDeclaration` named ``MIMEParams` (extends `Map`)`, but it does not yet have a dedicated description in the generated reference.
