.TH ORO-UTIL 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:util \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:util'
.fi
.SH DESCRIPTION
.PP
oro:util is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBTextDecoder\fR
This is an exported `VariableDeclaration` named `TextDecoder`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBTextEncoder\fR
This is an exported `VariableDeclaration` named `TextEncoder`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisArray\fR
This is an exported `VariableDeclaration` named `isArray`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBinspectSymbols\fR
This is an exported `VariableDeclaration` named `inspectSymbols`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBdebug(section)\fR
This is an exported `FunctionDeclaration` named `debug`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBhasOwnProperty(object, property)\fR
Tests whether an object owns a string or symbol property.
\fBParameters:\fR
.br
\fIobject\fR (object; required)
.br
\fIproperty\fR (string \\| number \\| symbol; required)
\fBReturns:\fR
.br
\fIboolean\fR
.TP
\fBisDate(object)\fR
This is an exported `FunctionDeclaration` named `isDate`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisTypedArray(object)\fR
This is an exported `FunctionDeclaration` named `isTypedArray`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisArrayLike(input)\fR
This is an exported `FunctionDeclaration` named `isArrayLike`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisError(object)\fR
This is an exported `FunctionDeclaration` named `isError`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisSymbol(value)\fR
This is an exported `FunctionDeclaration` named `isSymbol`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisNumber(value)\fR
This is an exported `FunctionDeclaration` named `isNumber`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisBoolean(value)\fR
This is an exported `FunctionDeclaration` named `isBoolean`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisArrayBufferView(buf)\fR
This is an exported `FunctionDeclaration` named `isArrayBufferView`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisAsyncFunction(object)\fR
This is an exported `FunctionDeclaration` named `isAsyncFunction`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisArgumentsObject(object)\fR
This is an exported `FunctionDeclaration` named `isArgumentsObject`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisEmptyObject(object)\fR
This is an exported `FunctionDeclaration` named `isEmptyObject`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisObject(object)\fR
This is an exported `FunctionDeclaration` named `isObject`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisUndefined(value)\fR
This is an exported `FunctionDeclaration` named `isUndefined`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisNull(value)\fR
This is an exported `FunctionDeclaration` named `isNull`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisNullOrUndefined(value)\fR
This is an exported `FunctionDeclaration` named `isNullOrUndefined`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisPrimitive(value)\fR
This is an exported `FunctionDeclaration` named `isPrimitive`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisRegExp(value)\fR
This is an exported `FunctionDeclaration` named `isRegExp`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisPlainObject(object)\fR
This is an exported `FunctionDeclaration` named `isPlainObject`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisArrayBuffer(object)\fR
This is an exported `FunctionDeclaration` named `isArrayBuffer`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisBufferLike(object)\fR
This is an exported `FunctionDeclaration` named `isBufferLike`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisFunction(value)\fR
This is an exported `FunctionDeclaration` named `isFunction`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisErrorLike(error)\fR
This is an exported `FunctionDeclaration` named `isErrorLike`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisClass(value)\fR
Tests whether a value is an ECMAScript class constructor.
\fBParameters:\fR
.br
\fIvalue\fR (unknown; required)
\fBReturns:\fR
.br
\fIboolean\fR
.TP
\fBisBuffer(value)\fR
This is an exported `FunctionDeclaration` named `isBuffer`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisPromiseLike(object)\fR
This is an exported `FunctionDeclaration` named `isPromiseLike`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBtoString(object)\fR
This is an exported `FunctionDeclaration` named `toString`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBtoBuffer(object, encoding)\fR
This is an exported `FunctionDeclaration` named `toBuffer`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBtoProperCase(string)\fR
This is an exported `FunctionDeclaration` named `toProperCase`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBsplitBuffer(buffer, highWaterMark)\fR
This is an exported `FunctionDeclaration` named `splitBuffer`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBclamp(value, min, max)\fR
This is an exported `FunctionDeclaration` named `clamp`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBpromisify(original)\fR
This is an exported `FunctionDeclaration` named `promisify`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBinspect(value, options)\fR
This is an exported `FunctionDeclaration` named `inspect`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBformat(format, ...args)\fR
This is an exported `FunctionDeclaration` named `format`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBparseJSON(string)\fR
This is an exported `FunctionDeclaration` named `parseJSON`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBparseHeaders(headers)\fR
This is an exported `FunctionDeclaration` named `parseHeaders`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBnoop()\fR
This is an exported `FunctionDeclaration` named `noop`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBIllegalConstructor\fR
This is an exported `ClassDeclaration` named `IllegalConstructor`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBisValidPercentageValue(input)\fR
This is an exported `FunctionDeclaration` named `isValidPercentageValue`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBcompareBuffers(a, b)\fR
This is an exported `FunctionDeclaration` named `compareBuffers`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBinherits(Constructor, Super)\fR
This is an exported `FunctionDeclaration` named `inherits`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBESM_TEST_REGEX\fR
This is an exported `VariableDeclaration` named `ESM_TEST_REGEX`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBdeprecate(..._args)\fR
This is an exported `FunctionDeclaration` named `deprecate`, but it does not yet have a dedicated description in the generated reference.
