.TH ORO-PATH-WELL-KNOWN 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:path/well\-known \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:path/well\-known'
.fi
.SH DESCRIPTION
.PP
oro:path/well\-known is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBDOWNLOADS\fR
Well known path to the user's "Downloads" folder.
.TP
\fBDOCUMENTS\fR
Well known path to the user's "Documents" folder.
.TP
\fBPICTURES\fR
Well known path to the user's "Pictures" folder.
.TP
\fBDESKTOP\fR
Well known path to the user's "Desktop" folder.
.TP
\fBVIDEOS\fR
Well known path to the user's "Videos" folder.
.TP
\fBMUSIC\fR
Well known path to the user's "Music" folder.
.TP
\fBRESOURCES\fR
Well known path to the application's "resources" folder.
.TP
\fBCONFIG\fR
Well known path to the application's "config" folder.
.TP
\fBMEDIA\fR
Well known path to the application's public "media" folder.
.TP
\fBDATA\fR
Well known path to the application's "data" folder.
.TP
\fBLOG\fR
Well known path to the application's "log" folder.
.TP
\fBTMP\fR
Well known path to the application's "tmp" folder.
.TP
\fBHOME\fR
Well known path to the application's "home" folder. This may be the user's HOME directory or the application container sandbox.
