.TH ORO-NODE-ESM-LOADER 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:node\-esm\-loader \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:node\-esm\-loader'
.fi
.SH DESCRIPTION
.PP
oro:node\-esm\-loader is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBresolve(specifier, _ctx, next)\fR
This is an exported `FunctionDeclaration` named `resolve`, but it does not yet have a dedicated description in the generated reference.
