.TH ORO-MIME-TYPE 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:mime/type \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:mime/type'
.fi
.SH DESCRIPTION
.PP
oro:mime/type is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBMIMEType\fR
This is an exported `ClassDeclaration` named `MIMEType`, but it does not yet have a dedicated description in the generated reference.
