.TH ORO-INTERNAL-USB-WEB 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:internal/usb\-web \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:internal/usb\-web'
.fi
.SH DESCRIPTION
.PP
oro:internal/usb\-web is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBinstallNavigatorUSB\fR
This is an exported `VariableDeclaration` named `installNavigatorUSB`, but it does not yet have a dedicated description in the generated reference.
