.TH ORO-SERVICE-WORKER 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:service\-worker \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:service\-worker'
.fi
.SH DESCRIPTION
.PP
oro:service\-worker is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBenv\fR
A reference to the opened environment. This value is an instance of an `Environment` if the scope is a ServiceWorker scope.
