.TH ORO-INTERNAL-TCP-SERVER-SOCKET 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:internal/tcp\-server\-socket \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:internal/tcp\-server\-socket'
.fi
.SH DESCRIPTION
.PP
oro:internal/tcp\-server\-socket is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBTCPServerSocket\fR
This is an exported `ClassDeclaration` named `TCPServerSocket`, but it does not yet have a dedicated description in the generated reference.
.TP
\fBopened()\fR
Documented method exposed by this module.
.TP
\fBclosed()\fR
Documented method exposed by this module.
