.TH ORO-INTERNAL-HID-WEB 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:internal/hid\-web \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:internal/hid\-web'
.fi
.SH DESCRIPTION
.PP
oro:internal/hid\-web is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBinstallNavigatorHID\fR
This is an exported `VariableDeclaration` named `installNavigatorHID`, but it does not yet have a dedicated description in the generated reference.
