.TH ORO-INTERNAL-BLUETOOTH-WEB 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:internal/bluetooth\-web \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:internal/bluetooth\-web'
.fi
.SH DESCRIPTION
.PP
oro:internal/bluetooth\-web is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBconstructor(options)\fR
Documented method exposed by this module.
\fBParameters:\fR
.br
\fIoptions\fR (object; optional)
.br
\fIoptions.id\fR (string; optional)
.br
\fIoptions.name\fR (string; optional)
.br
\fIoptions.services\fR (string[]; optional)
.br
\fIoptions.manufacturerData\fR (any; optional)
