.TH ORO-LATICA-CACHE 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:latica/cache \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:latica/cache'
.fi
.SH DESCRIPTION
.PP
oro:latica/cache is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBDEFAULT_MAX_SIZE\fR
Default max size of a `Cache` instance.
.TP
\fBdefaultSiblingResolver(a, b)\fR
Default cache sibling resolver that computes a delta between two entries clocks.
\fBParameters:\fR
.br
\fIa\fR (CacheEntry; required)
.br
\fIb\fR (CacheEntry; required)
\fBReturns:\fR
.br
\fInumber\fR
.TP
\fBCacheData (extends Map)\fR
Internal mapping of packet IDs to packet data used by `Cache`.
.TP
\fBCache\fR
A class for storing a cache of packets by ID. This class includes a scheme for reconciling disjointed packet caches in a large distributed system. The following are key design characteristics.
.br
Space Efficiency: This scheme can be space\-efficient because it summarizes the cache's contents in a compact binary format. By sharing these summaries, two computers can quickly determine whether their caches have common data or differences.
.br
Bandwidth Efficiency: Sharing summaries instead of the full data can save bandwidth. If the differences between the caches are small, sharing summaries allows for more efficient data synchronization.
.br
Time Efficiency: The time efficiency of this scheme depends on the size of the cache and the differences between the two caches. Generating summaries and comparing them can be faster than transferring and comparing the entire dataset, especially for large caches.
.br
Complexity: The scheme introduces some complexity due to the need to encode and decode summaries. In some cases, the overhead introduced by this complexity might outweigh the benefits, especially if the caches are relatively small. In this case, you should be using a query.
.br
Data Synchronization Needs: The efficiency also depends on the data synchronization needs. If the data needs to be synchronized in real\-time, this scheme might not be suitable. It's more appropriate for cases where periodic or batch synchronization is acceptable.
.br
Scalability: The scheme's efficiency can vary depending on the scalability of the system. As the number of cache entries or computers involved increases, the complexity of generating and comparing summaries will stay bound to a maximum of 16Mb.
.TP
\fBconstructor(data)\fR
`Cache` class constructor.
\fBParameters:\fR
.br
\fIdata\fR (CacheData?; optional)
.TP
\fBsize()\fR
Readonly count of the number of cache entries.
.TP
\fBbytes()\fR
Readonly size of the cache in bytes.
.TP
\fBinsert(k, v)\fR
Inserts a `CacheEntry` value `v` into the cache at key `k`.
\fBParameters:\fR
.br
\fIk\fR (string; required)
.br
\fIv\fR (CacheEntry; required)
\fBReturns:\fR
.br
\fIboolean\fR
.TP
\fBget(k)\fR
Gets a `CacheEntry` value at key `k`.
\fBParameters:\fR
.br
\fIk\fR (string; required)
\fBReturns:\fR
.br
\fICacheEntry?\fR
.TP
\fBdelete(k)\fR
Documented method exposed by this module.
\fBParameters:\fR
.br
\fIk\fR (string; required)
\fBReturns:\fR
.br
\fIboolean\fR
.TP
\fBhas(k)\fR
Predicate to determine if cache contains an entry at key `k`.
\fBParameters:\fR
.br
\fIk\fR (string; required)
\fBReturns:\fR
.br
\fIboolean\fR
.TP
\fBcompose(packet)\fR
Composes an indexed packet into a new `Packet`
\fBParameters:\fR
.br
\fIpacket\fR (Packet; required)
.TP
\fBsummarize(prefix)\fR
The summarize method returns a terse yet comparable summary of the cache contents.
.br
Think of the cache as a trie of hex characters, the summary returns a checksum for the current level of the trie and for its 16 children.
.br
This is similar to a merkel tree as equal subtrees can easily be detected without the need for further recursion. When the subtree checksums are inequivalent then further negotiation at lower levels may be required, this process continues until the two trees become synchonized.
.br
When the prefix is empty, the summary will return an array of 16 checksums these checksums provide a way of comparing that subtree with other peers.
.br
When a variable\-length hexidecimal prefix is provided, then only cache member hashes sharing this prefix will be considered.
.br
For each hex character provided in the prefix, the trie will decend by one level, each level divides the 2^128 address space by 16. For exmaple...
.br
Level 0 1 2 \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- 2b00 aa0e ━┓ ━┓ aa1b ┃ ┃ aae3 ┃ ┃ ━┓ aaea ┃ ┃ ┃ aaeb ┃ ━┛ ━┛ ab00 ┃ ━┓ ab1e ┃ ┃ ab2a ┃ ┃ abef ┃ ┃ abf0 ━┛ ━┛ bff9
\fBParameters:\fR
.br
\fIprefix\fR (string; required; default '') a string of lowercased hexidecimal characters
\fBReturns:\fR
.br
\fIObject\fR
.TP
\fBencodeSummary(summary)\fR
The encodeSummary method provides a compact binary encoding of the output of summary()
\fBParameters:\fR
.br
\fIsummary\fR (Object; required) the output of calling summary()
\fBReturns:\fR
.br
\fIBuffer\fR
.TP
\fBdecodeSummary(bin)\fR
The decodeSummary method decodes the output of encodeSummary()
\fBParameters:\fR
.br
\fIbin\fR (Buffer; required) the output of calling encodeSummary()
\fBReturns:\fR
.br
\fIObject\fR summary
.TP
\fBisValidSummaryHashFormat(hash)\fR
Test a summary hash format is valid
\fBParameters:\fR
.br
\fIhash\fR (string; required)
