.TH ORO-SERVICE-WORKER-DEBUG 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:service\-worker/debug \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:service\-worker/debug'
.fi
.SH DESCRIPTION
.PP
oro:service\-worker/debug is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBdebug(...args)\fR
This is an exported `FunctionDeclaration` named `debug`, but it does not yet have a dedicated description in the generated reference.
