.TH ORO-INTERNAL-SERVICE-WORKER 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:internal/service\-worker \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:internal/service\-worker'
.fi
.SH DESCRIPTION
.PP
oro:internal/service\-worker is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBserviceWorker\fR
This is an exported `VariableDeclaration` named `serviceWorker`, but it does not yet have a dedicated description in the generated reference.
