.TH ORO-INTERNAL-ITERATOR 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:internal/iterator \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:internal/iterator'
.fi
.SH DESCRIPTION
.PP
oro:internal/iterator is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBfromArray(items)\fR
Internal iterator utilities. Currently only provides a trivial iterator wrapper.
