.TH ORO-ASYNC-WRAP 3 "" "Oro Runtime" "Oro Runtime API Manual"
.SH NAME
oro:async/wrap \- JavaScript API module
.SH SYNOPSIS
.nf
import * as module from 'oro:async/wrap'
.fi
.SH DESCRIPTION
.PP
oro:async/wrap is a JavaScript API module exposed by the Oro Runtime.
.SH REFERENCE
.TP
\fBsymbol\fR
This is an exported `VariableDeclaration` named `symbol`, but it does not yet have a dedicated description in the generated reference.
