export const sep: "/" | "\\";
export const delimiter: ":" | ";";
export const resolve: typeof posix.win32.resolve;
export const join: typeof posix.win32.join;
export const dirname: typeof posix.win32.dirname;
export const basename: typeof posix.win32.basename;
export const extname: typeof posix.win32.extname;
export const cwd: typeof posix.win32.cwd;
export const isAbsolute: typeof posix.win32.isAbsolute;
export const parse: typeof posix.win32.parse;
export const format: typeof posix.win32.format;
export const normalize: typeof posix.win32.normalize;
export const relative: typeof posix.win32.relative;
declare const _default: typeof posix | typeof posix.win32;
export default _default;
import { posix } from './path/index.js';
import { Path } from './path/index.js';
import { win32 } from './path/index.js';
import { mounts } from './path/index.js';
import { DOWNLOADS } from './path/index.js';
import { DOCUMENTS } from './path/index.js';
import { RESOURCES } from './path/index.js';
import { PICTURES } from './path/index.js';
import { DESKTOP } from './path/index.js';
import { VIDEOS } from './path/index.js';
import { CONFIG } from './path/index.js';
import { MEDIA } from './path/index.js';
import { MUSIC } from './path/index.js';
import { HOME } from './path/index.js';
import { DATA } from './path/index.js';
import { LOG } from './path/index.js';
import { TMP } from './path/index.js';
export { Path, posix, win32, mounts, DOWNLOADS, DOCUMENTS, RESOURCES, PICTURES, DESKTOP, VIDEOS, CONFIG, MEDIA, MUSIC, HOME, DATA, LOG, TMP };
